source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'XZXDailyBlock' do

use_frameworks!

pod 'AFNetworking', '~> 3.0'
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'DKNightVersion'
pod 'Masonry'
pod 'ReactiveCocoa'
pod 'Realm'
pod 'SVProgressHUD'
pod 'YYText'

end