source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'XZXDailyBlock' do

pod 'AFNetworking', '~> 3.0'
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'DKNightVersion'
pod 'Masonry'
pod 'ReactiveCocoa', '2.5'
pod 'Realm'
pod 'SVProgressHUD'

end